# Form implementation generated from reading ui file 'D:\2025_2026\se1\machine\ML_K23416\Midterm\uis\StatisticMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelTitle = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelTitle.setGeometry(QtCore.QRect(10, 10, 780, 40))
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setStyleSheet("font: bold 18pt \"Segoe UI\"; color: #0055ff;")
        self.labelTitle.setObjectName("labelTitle")
        self.labelT1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelT1.setGeometry(QtCore.QRect(40, 70, 50, 20))
        self.labelT1.setObjectName("labelT1")
        self.dateEditT1 = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEditT1.setGeometry(QtCore.QRect(90, 65, 110, 26))
        self.dateEditT1.setObjectName("dateEditT1")
        self.labelT2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelT2.setGeometry(QtCore.QRect(220, 70, 50, 20))
        self.labelT2.setObjectName("labelT2")
        self.dateEditT2 = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateEditT2.setGeometry(QtCore.QRect(270, 65, 110, 26))
        self.dateEditT2.setObjectName("dateEditT2")
        self.labelN = QtWidgets.QLabel(parent=self.centralwidget)
        self.labelN.setGeometry(QtCore.QRect(410, 70, 60, 20))
        self.labelN.setObjectName("labelN")
        self.spinBoxN = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinBoxN.setGeometry(QtCore.QRect(470, 65, 60, 26))
        self.spinBoxN.setMinimum(1)
        self.spinBoxN.setMaximum(50)
        self.spinBoxN.setProperty("value", 5)
        self.spinBoxN.setObjectName("spinBoxN")
        self.btnInvoiceMax = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnInvoiceMax.setGeometry(QtCore.QRect(40, 110, 220, 30))
        self.btnInvoiceMax.setObjectName("btnInvoiceMax")
        self.btnTopCustomer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTopCustomer.setGeometry(QtCore.QRect(280, 110, 240, 30))
        self.btnTopCustomer.setObjectName("btnTopCustomer")
        self.btnChart = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnChart.setGeometry(QtCore.QRect(540, 110, 220, 30))
        self.btnChart.setObjectName("btnChart")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 160, 720, 380))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thống kê giao dịch"))
        self.labelTitle.setText(_translate("MainWindow", "BÁO CÁO THỐNG KÊ TRANSACTION"))
        self.labelT1.setText(_translate("MainWindow", "T1:"))
        self.labelT2.setText(_translate("MainWindow", "T2:"))
        self.labelN.setText(_translate("MainWindow", "Top N:"))
        self.btnInvoiceMax.setText(_translate("MainWindow", "Invoice có giá trị lớn nhất"))
        self.btnTopCustomer.setText(_translate("MainWindow", "Top N Customer theo T1–T2"))
        self.btnChart.setText(_translate("MainWindow", "Vẽ biểu đồ theo quốc gia"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hạng mục"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Kết quả"))
