# Form implementation generated from reading ui file 'D:\2025_2026\se1\machine\ML_K23416\MLBAProject\UI\DatabaseConnect.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 10, 201, 191))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 18, 35, 10))
        self.label.setObjectName("label")
        self.lineEditServer = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditServer.setGeometry(QtCore.QRect(50, 12, 141, 20))
        self.lineEditServer.setObjectName("lineEditServer")
        self.lineEditPort = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPort.setGeometry(QtCore.QRect(50, 40, 141, 20))
        self.lineEditPort.setObjectName("lineEditPort")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 46, 35, 10))
        self.label_2.setObjectName("label_2")
        self.lineEditDatabase = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditDatabase.setGeometry(QtCore.QRect(50, 70, 141, 20))
        self.lineEditDatabase.setObjectName("lineEditDatabase")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 76, 35, 10))
        self.label_3.setObjectName("label_3")
        self.lineEditUser = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditUser.setGeometry(QtCore.QRect(50, 100, 141, 20))
        self.lineEditUser.setObjectName("lineEditUser")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 106, 35, 10))
        self.label_4.setObjectName("label_4")
        self.lineEditPassword = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditPassword.setGeometry(QtCore.QRect(50, 130, 141, 20))
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 136, 35, 10))
        self.label_5.setObjectName("label_5")
        self.pushButtonConnect = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonConnect.setGeometry(QtCore.QRect(20, 160, 56, 17))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("D:\\2025_2026\\se1\\machine\\ML_K23416\\MLBAProject\\UI\\../Images/ic_connect.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonConnect.setIcon(icon)
        self.pushButtonConnect.setObjectName("pushButtonConnect")
        self.pushButtonClose = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonClose.setGeometry(QtCore.QRect(120, 160, 56, 17))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("D:\\2025_2026\\se1\\machine\\ML_K23416\\MLBAProject\\UI\\../Images/ic_close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonClose.setIcon(icon1)
        self.pushButtonClose.setObjectName("pushButtonClose")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Lê Hoàng Bảo Vy"))
        self.groupBox.setTitle(_translate("MainWindow", "Connection Setting:"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Server:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Port:</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Database:</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">User:</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:7pt;\">Password:</span></p></body></html>"))
        self.pushButtonConnect.setText(_translate("MainWindow", "Connect"))
        self.pushButtonClose.setText(_translate("MainWindow", "Close"))
